title: Your awesome title
author:
  name: Samuele Papa
  email: s.papa@uva.nl
description: > # this means to ignore newlines until "show_excerpts:"
  The Deep Thinking Hour is an event at the University of Amsterdam, organized by the gorup lead by Efstratios Gavves. Researchers and students come together to
  discuss and learn about the state-of-the-art in Deep Learning. Generative models, dynamical systems, geometric deep learning are the main focus.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
    - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
